# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 88e8a1c5f9dd80249ff20962362594a2efe5eed594982a7b5138d31582846b16f8f7bc788f8a26480fd2cab92b1000572cdeef61b300519ab60e101e1ab3039c

test:
  secret_key_base: 86aae7b16d0e8a8dfb2e1346ca78f30f38ad08b7ca446a680404f64ad2d130b36d35b17bab1cf6f90ee9447878ca877d263631d7e218b4a6f00351117d33a5b6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
